### ISSUE TITLE
X11 needed?

### ISSUE THREAD

**Issue by m9dfukc** [roymacdonald/ofxDLib#6]
I'm trying to compile this under OsX 10.11 with no success. I'm always getting the "nativefont.h X11/Xlib.h file not found" error.

Seems X11 is needed if you wanna use ofXDLib?! On the other side, I just tried ofxLearn which comes without this requirement.

**Comment by roymacdonald** [comment]
Hi,
I think is because ofxLearn uses an older version of dlib. 
Initially I installed X11 but soon realized that you can disable the need for it if you disable the gui support for dlib. add `#define DLIB_NO_GUI_SUPPORT` to dlib's source.cpp. If this doesn't work, also remove all  the paths to  X11 in the xcode project .  Let me know how it goes. I'm not on 10.11 but I'll try to borrow a machine with that OS for testing. 
Best

**Comment by m9dfukc** [comment]
Jep, got it running by adding `#define DLIB_NO_GUI_SUPPORT` to dlib's source.cpp. Maybe you can add this to the README.
Also I can confirm that it works under OsX 10.11. Thanks!

**Comment by roymacdonald** [comment]
fixed in the apothecary scripts.
